# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Trivia Patente' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'

  # Pods for Trivia Patente

  target 'Trivia PatenteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Trivia PatenteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
